# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &c홈 &6| &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

  # 홈을 지정 하였을 때 출력되는 메세지
  setHome: '&f{slot}번 홈을 지정했습니다.'

  # 홈을 삭제 하였을 때 출력되는 메세지
  removeHome: '&f{slot}번 홈을 삭제했습니다.'

  # 홈으로 텔레포트 하였을 때 출력되는 메세지
  teleportHome: '&f{slot}번 홈으로 텔레포트 하였습니다.'

  # 홈으로 텔레포트 할때 남은 시간을 출력하는 메세지
  sendLeftTime: '&f{time}초 남았습니다.'

  # 홈으로 텔레포트 할때 움직이면 출력되는 메세지
  onMoveInTelePort: '&f움직임으로 인해 텔레포트가 취소되었습니다'

  # 성공적으로 값을 세팅했을때 출력되는 메세지
  setValueSuccessfully: '&a성공적으로 설정되었습니다'

errorMessages:
  # 권한이 없을 때 출력되는 메시지
  noPermission: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'

  # 콘솔에서 사용하지 못하는 명령어를 사용하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 사용할 수 없는 명령어입니다.'

  # 삭제하려는 슬롯에 정보가 없을때 출력되는 메세지
  noHomeInSlot: '&c삭제하려는 슬롯은 비어있습니다.'

  # 텔레포트하려는 슬롯에 정보가 없을때 출력되는 메세지
  noHomeInTelePortSlot: '&c텔레포트하려는 슬롯은 비어있습니다.'

  # 생성하려는 슬롯에 정보가 이미 존재 할때 출력되는 메세지
  alreadyHomeInSlot: '&c생성하려는 슬롯에 정보가 이미 존재합니다.'

  # 유효하지 않는 값 입력
  inputInvalidValue: '&c유효하지 않는 값을 입력했습니다.'

data:
  # 홈까지 이동하는 시간 (단위: 초 / 값이 0이면 바로이동)
  time: 5

  # 홈까지 이동할때 움직임 감지를 넣을건지
  move: true