# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &c홈 &6| &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

errorMessages:
  # 권한이 없을 때 출력되는 메시지
  noPermission: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'

  # 콘솔에서 사용하지 못하는 명령어를 사용하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 사용할 수 없는 명령어입니다.'