name: ST-Home
main: net.starly.home.HomeMain
author: Starly Team
website: http://starly.kr/

description: Home Plugin.

depend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  home:
    aliases: [ ν™ ]

  homeSetting:
    aliases: [ ν™μ„Έν… ]